apps/persona/urls.py
# persona/urls.py
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from .views import list, add, edit, autocomplite, updateOrdenHappy

app_name = "persona"

urlpatterns = [
    # Incluye las URLs de API desde el archivo separado
    path("api/", include("apps.persona.API.urls", namespace="api")),
    # Rutas no relacionadas con la API
    path("list/", (list), name="list"),
    path("add/", login_required(add), name="add"),
    path("edit/<int:pk>", login_required(edit), name="edit"),
    path("autocomplite/", login_required(autocomplite), name="autocomplite"),
    path(
        "update/orden/happy",
        login_required(updateOrdenHappy),
        name="update-orden-happy",
    ),
]

apps/viaje/API/urls.py
# viaje/API/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import (
    ProgramacionViajeViewSet,
    ProgramacionAsientoViewSet,
    EmbarqueViewSet,
    ManifiestoViewSet,
    ReservarAsientoView,
)

app_name = "api"

router = DefaultRouter()
router.register(
    "programaciones", ProgramacionViajeViewSet, basename="programacionviaje"
)
router.register("asientos", ProgramacionAsientoViewSet, basename="programacionasiento")
router.register("embarques", EmbarqueViewSet, basename="embarque")
router.register("manifiestos", ManifiestoViewSet, basename="manifiesto")

urlpatterns = [
    # Rutas generales de la API
    path("reservar-asiento/", ReservarAsientoView.as_view(), name="reservar-asiento"),
]

# Agregamos las rutas del router
urlpatterns += router.urls

apps/viaje/urls.py
# viaje/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import (
    embarqueAdd,
    embarqueList,
    embarqueEdit,
    programa_add,
    manifiestoEdit,
    programaEdit,
    programaList,
    programaAsientoEdit,
    programaAsientoList,
    manifiestoPrint,
    embarqueCambiar,
    embarquePrint,
)

app_name = "viaje"

urlpatterns = [
    # Incluye las URLs de API desde el archivo separado
    path("api/", include("apps.viaje.API.urls", namespace="api")),
    # Rutas no relacionadas con la API
    path("embarque/add/", login_required(embarqueAdd), name="embarque-add"),
    path("embarque/list/", login_required(embarqueList), name="embarque-list"),
    path("embarque/edit/", login_required(embarqueEdit), name="embarque-edit"),
    path("embarque/cambiar/", login_required(embarqueCambiar), name="embarque-cambiar"),
    path("embarque/print/", login_required(embarquePrint), name="embarque-print"),
    path("programa/list/", login_required(programaList), name="programa-list"),
    path("programa/add/", login_required(programa_add), name="programa-add"),
    path("programa/edit/", login_required(programaEdit), name="programa-edit"),
    path(
        "programa/asiento/edit/",
        login_required(programaAsientoEdit),
        name="programa-asiento-edit",
    ),
    path(
        "programa/asiento/list/",
        login_required(programaAsientoList),
        name="programa-asiento-list",
    ),
    path("manifiesto/edit/", login_required(manifiestoEdit), name="manifiesto-edit"),
    path("manifiesto/print/", login_required(manifiestoPrint), name="manifiesto-print"),
]

django_moda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Swagger
from drf_yasg import openapi
from drf_yasg.views import get_schema_view as swagger_get_schema_view


handler403 = "apps.sistema.views.custom_permission_denied_view"

schema_view = swagger_get_schema_view(
    openapi.Info(
        title="Moda Tours API",
        default_version="1.0",
        description="Moda Tours API Documentation",
    ),
    public=True,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("persona/", include("apps.persona.urls", namespace="persona")),
    path("envio/", include("apps.envio.urls", namespace="envio")),
    path("viaje/", include("apps.viaje.urls", namespace="viaje")),
    path("tesoreria/", include("apps.caja.urls", namespace="caja")),
    path("", include("apps.web.urls", namespace="web")),
    path("sistema/", include("apps.sistema.urls", namespace="sistema")),
    path("facturacion/", include("apps.facturacion.urls", namespace="facturacion")),
    path(
        "catalogosunat/", include("apps.catalogoSunat.urls", namespace="catalogosunat")
    ),
    path("empresa/", include("apps.empresa.urls", namespace="empresa")),
    path(
        "api/v1/",
        include(
            [
                path(
                    "swagger/schema/",
                    schema_view.with_ui("swagger", cache_timeout=0),
                    name="swagger-schema",
                ),
                path("persona/", include("apps.persona.urls", namespace="persona")),
                path("envio/", include("apps.envio.urls", namespace="envio")),
                path("viaje/", include("apps.viaje.urls", namespace="viaje")),
                path("tesoreria/", include("apps.caja.urls", namespace="caja")),
                path("", include("apps.web.urls", namespace="web")),
                path("sistema/", include("apps.sistema.urls", namespace="sistema")),
                path(
                    "facturacion/",
                    include("apps.facturacion.urls", namespace="facturacion"),
                ),
                path(
                    "catalogosunat/",
                    include("apps.catalogoSunat.urls", namespace="catalogosunat"),
                ),
                path("empresa/", include("apps.empresa.urls", namespace="empresa")),
            ]
        ),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/viaje/models.py
from django.db import models
from django.forms import model_to_dict
from apps.venta.models import Movimiento
from apps.persona.models import Persona
from apps.empresa.models import Agencia, Vehiculo, Conductor, Asiento


class ProgramacionViaje(models.Model):
    nombreViaje = models.CharField(max_length=100, blank=True, null=True)
    rutaOrigen = models.ForeignKey(Agencia, on_delete=models.PROTECT)
    rutaDestino = models.ForeignKey(
        Agencia, on_delete=models.PROTECT, related_name="destino_viaje"
    )
    fechaViaje = models.DateField()
    horaViaje = models.TimeField(default="12:00")
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.PROTECT)
    piloto = models.ForeignKey(
        Conductor, on_delete=models.PROTECT, blank=True, null=True
    )
    copiloto = models.ForeignKey(
        Conductor,
        on_delete=models.PROTECT,
        blank=True,
        null=True,
        related_name="copiloto_viaje",
    )
    ayudante = models.ForeignKey(
        Persona, on_delete=models.PROTECT, blank=True, null=True
    )
    terramosa = models.ForeignKey(
        Persona,
        on_delete=models.PROTECT,
        blank=True,
        null=True,
        related_name="terramosa_viaje",
    )
    precio = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    activo = models.BooleanField(default=True)

    class Meta:
        verbose_name = "ProgramacionViaje"
        verbose_name_plural = "ProgramacionViajes"

    def __str__(self):
        return self.nombreViaje

    def save(self, *args, **kwargs):
        self.nombreViaje = f"{self.rutaOrigen.nombre}-{self.rutaDestino.nombre}"
        return super(ProgramacionViaje, self).save(*args, **kwargs)

    def toJson(self):
        return model_to_dict(self)


Estado = {
    ("vendido", "Vendido"),
    ("libre", "Libre"),
    ("reservado", "Reservado"),
    ("cortesia", "Cortesía"),
}


class ProgramacionAsiento(models.Model):
    programacionViaje = models.ForeignKey(
        ProgramacionViaje, on_delete=models.PROTECT, blank=True, null=True
    )
    asiento = models.ForeignKey(
        Asiento, on_delete=models.PROTECT, blank=True, null=True
    )
    estado = models.CharField(max_length=30, choices=Estado, default="libre")
    precio = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)

    class Meta:
        verbose_name = "ProgramacionAsiento"
        verbose_name_plural = "ProgramacionAsientos"

    def __str__(self):
        return self.estado

    def toJson(self):
        return model_to_dict(self)


class Embarque(models.Model):
    numDocumento = models.CharField(max_length=8, blank=True, null=True)
    programacionViaje = models.ForeignKey(
        ProgramacionViaje, on_delete=models.PROTECT, blank=True, null=True
    )
    venta = models.OneToOneField(
        Movimiento, on_delete=models.PROTECT, blank=True, null=True
    )
    pasajero = models.ForeignKey(Persona, on_delete=models.PROTECT)
    lugar_abordo = models.ForeignKey(
        Agencia,
        verbose_name="Embarque",
        on_delete=models.PROTECT,
        blank=True,
        null=True,
    )
    lugar_bajada = models.ForeignKey(
        Agencia,
        verbose_name="Desembarque",
        on_delete=models.PROTECT,
        related_name="embarque_bajada",
        blank=True,
        null=True,
    )
    hora_abordo = models.TimeField(default="12:00")
    observacion = models.TextField(verbose_name="Observaciones", blank=True, null=True)
    numAsiento = models.CharField(max_length=2)
    precio = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    enSala = models.BooleanField(
        verbose_name="El pasajero esta en sala?", default=False
    )
    telefono = models.CharField(max_length=50, blank=True, null=True)
    escambio = models.BooleanField(default=False)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    usuario = models.ForeignKey(
        Persona,
        on_delete=models.PROTECT,
        related_name="embarque_usuario",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Embarque"
        verbose_name_plural = "Embarques"

    def __str__(self):
        return self.numDocumento


class Manifiesto(models.Model):
    numDocumento = models.CharField(max_length=8, blank=True, null=True)
    direccion = models.CharField(max_length=150, blank=True, null=True)
    fechaViaje = models.DateField(blank=True, null=True)
    vehiculo = models.ForeignKey(
        Vehiculo, on_delete=models.PROTECT, blank=True, null=True
    )
    piloto = models.ForeignKey(
        Conductor, on_delete=models.PROTECT, blank=True, null=True
    )
    copiloto = models.ForeignKey(
        Conductor,
        on_delete=models.PROTECT,
        blank=True,
        null=True,
        related_name="copiloto_manifiesto",
    )
    programacionViaje = models.OneToOneField(
        ProgramacionViaje, on_delete=models.PROTECT, blank=True, null=True
    )
    usuario = models.ForeignKey(
        Persona, on_delete=models.PROTECT, blank=True, null=True
    )
    modalidaServicio = models.CharField(
        max_length=30, default="Regular", blank=True, null=True
    )
    seGenero = models.BooleanField(default=False)
    embarque = models.ManyToManyField(Embarque, blank=True)
    printRutaOrigen = models.ForeignKey(
        Agencia,
        related_name="manifiesto_printrutaorigin",
        verbose_name="De",
        on_delete=models.PROTECT,
        blank=True,
        null=True,
    )
    printRutaFinal = models.ManyToManyField(
        Agencia,
        through="ManifiestoRutaFinal",
        verbose_name="Destinos[*** Si va a guardar nuevos destinos, deseleccione todo y vuelva a seleccionar]",
        blank=True,
        null=True,
    )
    create = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    update = models.DateTimeField(auto_now=True, blank=True, null=True)

    class Meta:
        verbose_name = "Manifiesto"
        verbose_name_plural = "Manifiestos"

    def __str__(self):
        return self.numDocumento


class ManifiestoRutaFinal(models.Model):
    manifiesto = models.ForeignKey(Manifiesto, on_delete=models.CASCADE)
    agencia = models.ForeignKey(Agencia, on_delete=models.CASCADE)
    orden = models.SmallIntegerField(null=True, blank=True)

    def __str__(self):
        return str(self.id)

apps/viaje/forms.py
from django import forms
from .models import Embarque, ProgramacionViaje, ProgramacionAsiento, Manifiesto
from apps.persona.models import Persona


class EmbarqueForm(forms.ModelForm):
    idprograma = forms.CharField()
    idasiento = forms.CharField(widget=forms.HiddenInput())
    pasajero = forms.ModelChoiceField(
        queryset=Persona.objects.filter(numDoc="44319644"),
        empty_label="Select an author",
    )

    class Meta:
        model = Embarque
        fields = "__all__"

        labels = {"programacionViaje": "Ruta"}

        widgets = {
            "numAsiento": forms.TextInput(
                attrs={"readonly": True, "value": "0", "class": "estetica"}
            ),
            "precio": forms.NumberInput(attrs={"class": "estetica"}),
            "lugar_abordo": forms.Select(attrs={"class": "select"}),
            "lugar_bajada": forms.Select(attrs={"class": "select"}),
            "hora_abordo": forms.DateTimeInput(attrs={"type": "time"}),
        }

    def clean_numAsiento(self):
        numAsiento = self.cleaned_data.get("numAsiento")

        if numAsiento == "0":
            raise forms.ValidationError("Tienes que elegir un numero de asiento")
        return numAsiento

    def clean_precio(self):
        precio = self.cleaned_data.get("precio")

        if precio <= 0:
            raise forms.ValidationError("Ingrese un precio adecuado")
        return precio

    def clean_idasiento(self):
        idasiento = int(self.cleaned_data.get("idasiento"))
        asiento = ProgramacionAsiento.objects.get(id=idasiento, estado="libre")

        if not asiento:
            raise forms.ValidationError("El asiento ya esta ocupado, seleccione otro!")
        return idasiento


class EmbarqueEditForm(forms.ModelForm):
    class Meta:
        model = Embarque
        # fields = '__all__'
        exclude = ["numDocumento", "venta", "precio", "pasajero"]
        widgets = {
            "numAsiento": forms.TextInput(
                attrs={"readonly": True, "value": "0", "class": "estetica"}
            ),
            "hora_abordo": forms.DateTimeInput(attrs={"type": "time"}),
        }


class ProgramacionViajeForm(forms.ModelForm):
    class Meta:
        model = ProgramacionViaje
        fields = "__all__"

        labels = {"fechaViaje": "Fecha de viaje"}

        widgets = {
            "fechaViaje": forms.DateInput(attrs={"type": "date"}),
            "horaViaje": forms.DateTimeInput(attrs={"type": "time"}),
        }


class BuscarViajeForm(forms.ModelForm):
    class Meta:
        model = ProgramacionViaje
        fields = ("rutaOrigen", "rutaDestino", "fechaViaje", "activo")

        widgets = {"fechaViaje": forms.DateInput(attrs={"type": "date"})}


class ManifiestoForm(forms.ModelForm):
    class Meta:
        model = Manifiesto
        exclude = [
            "numDocumento",
            "programacionViaje",
        ]

        widgets = {"fechaViaje": forms.DateInput(attrs={"type": "date"})}


class ProgramacionAsientoForm(forms.ModelForm):
    idasiento = forms.CharField(required=False)

    class Meta:
        model = ProgramacionAsiento
        fields = "__all__"

templates/apps/viaje/programa/add.html
{% extends "layouts/base-demo.html" %}

{% block title %} Nuevo Programa {% endblock %} 

<!-- Plugins CSS goes HERE  -->
{% block css %}
{% endblock css %}

{% block breadcrumb %}
<div class="nav-content px5 red lighten-1">
  <a href="#!" class="breadcrumb">Home</a>
  <a href="{% url 'persona:list' %}" class="breadcrumb">Pasaje</a>
  <a href="{% url 'persona:list' %}" class="breadcrumb">Programación</a>
  <a href="#!" class="breadcrumb">Nuevo</a>
</div>
{% endblock breadcrumb %}

{% block content %}
<div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                
            <form method="POST" enctype="multipart/form-data" class="section77">
                {% csrf_token %}
              <div class="card">
                <div class="card-content white-text">
                  <span class="card-title color-primary-text">Nueva Programación de Viaje</span>
                  
                    <div class="row">
                        <div class="input-field col s12 m12 l6">
                            {{programa.rutaOrigen}}
                            {{programa.rutaOrigen.label_tag}}
                            {{programa.rutaOrigen.errors}} 
                            
                            
                        </div>
                        <div class="input-field col s12 m12 l6">
                            {{programa.rutaDestino}}
                            {{programa.rutaDestino.label_tag}}
                            {{programa.rutaDestino.errors}} 
                            
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m12 l5">
                            {{programa.piloto}}
                            {{programa.piloto.label_tag}}
                        </div>
                        <div class="input-field col s12 m12 l5">
                            {{programa.copiloto}}
                            {{programa.copiloto.label_tag}}
                        </div>
                        <div class="input-field col s12 m12 l2">
                            {{programa.vehiculo}}
                            {{programa.vehiculo.label_tag}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m12 l4">
                            {{programa.fechaViaje}}
                            {{programa.fechaViaje.label_tag}}
                        </div>
                        <div class="input-field col s12 m12 l4">
                            {{programa.horaViaje}}
                            {{programa.horaViaje.label_tag}}
                        </div>
                        
                        <div class="input-field col s12 m12 l4">
                            {{programa.precio}}
                            {{programa.precio.label_tag}}
                        </div>
                    </div>

                </div>
                <div class="card-action">                    
                    <a href="#" class="btn color-secundary">Cancelar</a>
                    <button class="btn waves-effect waves-light color-primary" type="submit" name="action">Guardar
                        <i class="material-icons right">send</i>
                    </button> 
                </div>
              </div>
            </form>
            </div>
          </div>

    
</div>

{% endblock content %}

{% block js %}

    <script>
        
        $(document).ready(function(){          

            $('select').formSelect();

            $('#id_tipoDoc').removeAttr("required");


        });  
    </script>

    {% if messages %}
    {% for m in messages %}
        <script>
            visibleAlert(
                title="Correcto!!",
                text="{{m}}",
                icon="{{m.tags}}"        
            )
        </script>
    {% endfor %}
    {% endif %}

{% endblock js %}

templates/apps/viaje/programa/asiento-list.html
{% extends "layouts/base-demo.html" %}
{% load my_templatetag %}

{% block title %} Register {% endblock %} 

<!-- Plugins CSS goes HERE  -->
{% block css %}
<style>
    .masOpcionVisible{        
        display: none;
    }
    input:required {
  background-color: yellow;

}
.input-field {
    position: relative;
    margin-top: 0.8rem;
    margin-bottom: 0rem; 
}
.card .card-content {
    padding: 0px 20px 0px 20px; 
}
.carro{
    border: solid 3px #d50000;
    padding-left: 20px;
    border-radius: 20px;
}
.columnacarro{
    margin-right: 5px;
    margin-bottom: 1px;
    /*cursor: pointer;*/
}

/* estados de asiento */
.pasadiso{
    background-color: #fffde7;
    width: 8% !important;
}

.cortesia{
    background-color: #ff5722;
}

.vendido{
    background-color: #ffd600 ;
}

.libre{
    background-color: #69f0ae ;
    
}

.reservado{
    background-color: #1e88e5 ;
}
.estetica{
    font-size: 3rem !important;
    height: 3rem !important;
    background-color: #78909c  !important;
    color: #ffffff  !important;
    border-radius: 20px !important;
    margin-top: 5px !important;
    padding-left: 10px !important;
}


</style>    
{% endblock css %}

{% block breadcrumb %}
    <div class="nav-content px5 red lighten-1">
    <a href="#" class="breadcrumb">Home</a>
    <a href="#" class="breadcrumb">Viaje</a>
    <a href="#" class="breadcrumb">Programación</a>
    <a href="#!" class="breadcrumb">Asientos</a>
    <a href="#!" class="breadcrumb">Listar</a>
    </div>
{% endblock breadcrumb %}

{% block content %}

{% if boleto.errors %}
    {% for m in boleto.errors %}
    {{m}}        
    {% endfor %}  
{% endif %}
<div class="container">
    
<div class="row" >
    <div class="col s12 m12">
        <div class="card yellow lighten-5">
        <div class="card-content white-text">
            <span class="card-title color-primary-text">Editar Asiento</span> 
            <div class="section z-depth-3 carro">          
                
                {% for asientoP in viajeProgramado %}
                    
                    {% if asientoP.asiento.codigoMatrix == 11 %}
                        <div class="row filacarro">
                        <div class="col s{{anchoColumna}} columnacarro {{asientoP.estado}}" asiento ='{{asientoP.asiento.numero}}' precio ='{{asientoP.precio}}' idasiento={{asientoP.id}}>
                            <p class="flow-text"><b>{{asientoP.asiento.numero | nonep}}</b></p>
                            <p class="center">
                            <span class="center">{{asientoP.precio | nonep}}</span>
                        </p>
                            
                        </div> 
                    {% else %}
                        {% if asientoP.asiento.saltofila %}
                            </div>
                            <div class="row filacarro">
                                <div class="col s{{anchoColumna}} columnacarro {{asientoP.estado}}" asiento ='{{asientoP.asiento.numero}}' precio ='{{asientoP.precio}}' idasiento={{asientoP.id}}>
                                    <p class="flow-text"><b>{{asientoP.asiento.numero | nonep}}</b></p>
                                    <p class="center">
                                        <span class="center">{{asientoP.precio | nonep}}</span>
                                    </p>
                                </div>
                        {% else %}  
                            <div class="col s{{anchoColumna}} columnacarro {{asientoP.estado}}" asiento ='{{asientoP.asiento.numero}}' precio ='{{asientoP.precio}}' idasiento={{asientoP.id}}>
                                <a href="/viaje/programa/asiento/edit/?fromCityName=Tarapoto%20%28Todos%29&fromCityId=195648&toCityName=Lima%20%28Todos%29&toCityId=195105&onward=20-Jan-2022&pk_asiento={{asientoP.id}}&srcCountry=PER&destCountry=PER&opId=0&busType=Any">
                                    <p class="flow-text"><b>{{asientoP.asiento.numero | nonep}}</b></p>
                                    <p class="center">
                                        <span class="center">{{asientoP.precio | nonep}}</span>
                                    </p>
                                </a>
                            </div> 
                        {% endif %}
                    {% endif %}                            
                {% endfor %}

                {% for asientoP in asientoProgramado %}
                           
                           {% if asientoP.asiento.codigoMatrix == 11 %}
                                <div class="row filacarro">
                                <div class="col s{{anchoColumna}} columnacarro {{asientoP.estado}}" asiento ='{{asientoP.asiento.numero}}' precio ='{{asientoP.precio}}' idasiento={{asientoP.id}}>
                                    <p class="flow-text"><b>{{asientoP.asiento.numero | nonep}}</b></p>
                                    <p class="center">
                                    <span class="center">{{asientoP.precio | nonep}}</span>
                                </p>
                                    
                                </div> 
                            {% else %}
                                {% if asientoP.asiento.saltofila %}
                                    </div>
                                    <div class="row filacarro">
                                        <div class="col s{{anchoColumna}} columnacarro {{asientoP.estado}}" asiento ='{{asientoP.asiento.numero}}' precio ='{{asientoP.precio}}' idasiento={{asientoP.id}}>
                                            <a href="/viaje/programa/asiento/edit/?fromCityName=Tarapoto%20%28Todos%29&fromCityId=195648&toCityName=Lima%20%28Todos%29&toCityId=195105&onward=20-Jan-2022&pk_asiento={{asientoP.id}}&srcCountry=PER&destCountry=PER&opId=0&busType=Any">
                                            <p class="flow-text"><b>{{asientoP.asiento.numero | nonep}}</b></p>
                                            <p class="center">
                                                <span class="center">{{asientoP.precio | nonep}}</span>
                                            </p>
                                            </a>
                                        </div>
                                {% else %}  
                                    <div class="col s{{anchoColumna}} columnacarro {{asientoP.estado}}" asiento ='{{asientoP.asiento.numero}}' precio ='{{asientoP.precio}}' idasiento={{asientoP.id}}>
                                        <a href="/viaje/programa/asiento/edit/?fromCityName=Tarapoto%20%28Todos%29&fromCityId=195648&toCityName=Lima%20%28Todos%29&toCityId=195105&onward=20-Jan-2022&pk_asiento={{asientoP.id}}&srcCountry=PER&destCountry=PER&opId=0&busType=Any">
                                        <p class="flow-text"><b>{{asientoP.asiento.numero | nonep}}</b></p>
                                        <p class="center">
                                            <span class="center">{{asientoP.precio | nonep}}</span>
                                        </p>
                                        </a>
                                    </div> 
                                {% endif %}
                           {% endif %}                            
                        {% endfor %}
            </div>            
        </div>
        <div class="card-content " style="padding-bottom: 10px; margin-top: 30px;">
            <span class="card-title color-primary-text">Leyenda de colores</span> 
            <div class="row">
                <div class="col s2 libre columnacarro" >Libre</div>
                <div class="col s2 vendido columnacarro">Vendido</div>
                <div class="col s2 reservado columnacarro">Reservado</div>
                <div class="col s2 cortesia columnacarro">Cortesía</div>
                </div>
        </div>
        
        <div class="card-action">
            <a href="{% url 'viaje:programa-list' %}"> < Atras</a>
        </div> 
        </div>
    </div>
    </div>

</div>

</div>


{% endblock content %}

{% block js %}

    <script>
        var cond = true
        
        $(document).ready(function(){        
           
            $('select').formSelect();
            $('#id_pasajero').removeAttr("required");
            $('.pasadiso').empty();

            $('.columnacarro11212').click(function(){

                let asiento = $(this).attr('asiento');
                let precio = $(this).attr('precio')
                let idasiento = $(this).attr('idasiento')

                preciotxt = precio.split(',')
                precioNumber=preciotxt[0]+"."+preciotxt[1]

                $("#{{boleto.precio.auto_id}}").val(parseFloat(precioNumber))

                $('#id_idasiento').val(idasiento)

                $("#{{boleto.numAsiento.auto_id}}").val(asiento)
                
            })
        }); 
        
        function precioAsiento(asiento,precio){

            $('#{{boleto.numAsiento.auto_id}}').val(asiento)
            $('._asiento').html("Asiento: <b>"+asiento+"</b")
              
        }

    </script>

    {% if messages %}
    {% for m in messages %}
        <script>
            visibleAlert(
                title="",
                text="{{m}}",
                icon="{{m.tags}}"        
            )
        </script>
    {% endfor %}
    {% endif %}




</script>
{% endblock js %}


<!-- https://www.youtube.com/watch?v=wRNzGxbeuX8-->