apps/persona/API/urls.py
# persona/API/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import (
    PersonaJuridicaAPIView,
    PersonaNaturalAPIView,
    PersonaViewSet,
    PersonaListCreateAPIView,
    PersonaRetrieveUpdateDestroyAPIView,
)

app_name = "api"

router = DefaultRouter()
router.register(r"personas", PersonaViewSet)

urlpatterns = [
    # Rutas generales de la API
    path("persona-natural/", PersonaNaturalAPIView.as_view(), name="persona-natural"),
    path(
        "persona-juridica/", PersonaJuridicaAPIView.as_view(), name="persona-juridica"
    ),
    path("personas/", PersonaListCreateAPIView.as_view(), name="persona-list-create"),
    path(
        "personas/<int:pk>/",
        PersonaRetrieveUpdateDestroyAPIView.as_view(),
        name="persona-detail",
    ),
]

# Agregamos las rutas del router
urlpatterns += router.urls

apps/persona/urls.py
# persona/urls.py
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from .views import list, add, edit, autocomplite, updateOrdenHappy

app_name = "persona"

urlpatterns = [
    # Incluye las URLs de API desde el archivo separado
    path("api/", include("apps.persona.API.urls", namespace="api")),
    # Rutas no relacionadas con la API
    path("list/", (list), name="list"),
    path("add/", login_required(add), name="add"),
    path("edit/<int:pk>", login_required(edit), name="edit"),
    path("autocomplite/", login_required(autocomplite), name="autocomplite"),
    path(
        "update/orden/happy",
        login_required(updateOrdenHappy),
        name="update-orden-happy",
    ),
]

apps/sistema/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    userAdd,
    userList,
    accountLogin,
    accountLoggout,
    menuList,
    userAgencia,
    homeIndex,
)

app_name = "sistema"
urlpatterns = [
    path("user/add", login_required(userAdd), name="user-add"),
    path("user/list", login_required(userList), name="user-list"),
    path("user/agencia/list", login_required(userAgencia), name="user-agencia-list"),
    path("account/login", accountLogin, name="account-login"),
    path("account/loggout", login_required(accountLoggout), name="account-loggout"),
    path("menu/list", login_required(menuList), name="menu-list"),
    path("", login_required(homeIndex), name="home-index"),
]

django_moda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Swagger
from drf_yasg import openapi
from drf_yasg.views import get_schema_view as swagger_get_schema_view


handler403 = "apps.sistema.views.custom_permission_denied_view"

schema_view = swagger_get_schema_view(
    openapi.Info(
        title="Moda Tours API",
        default_version="1.0",
        description="Moda Tours API Documentation",
    ),
    public=True,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("persona/", include("apps.persona.urls", namespace="persona")),
    path("envio/", include("apps.envio.urls", namespace="envio")),
    path("viaje/", include("apps.viaje.urls", namespace="viaje")),
    path("tesoreria/", include("apps.caja.urls", namespace="caja")),
    path("", include("apps.web.urls", namespace="web")),
    path("sistema/", include("apps.sistema.urls", namespace="sistema")),
    path("facturacion/", include("apps.facturacion.urls", namespace="facturacion")),
    path(
        "catalogosunat/", include("apps.catalogoSunat.urls", namespace="catalogosunat")
    ),
    path("empresa/", include("apps.empresa.urls", namespace="empresa")),
    path(
        "api/v1/",
        include(
            [
                path(
                    "swagger/schema/",
                    schema_view.with_ui("swagger", cache_timeout=0),
                    name="swagger-schema",
                ),
                path("persona/", include("apps.persona.urls", namespace="persona")),
                path("envio/", include("apps.envio.urls", namespace="envio")),
                path("viaje/", include("apps.viaje.urls", namespace="viaje")),
                path("tesoreria/", include("apps.caja.urls", namespace="caja")),
                path("", include("apps.web.urls", namespace="web")),
                path("sistema/", include("apps.sistema.urls", namespace="sistema")),
                path(
                    "facturacion/",
                    include("apps.facturacion.urls", namespace="facturacion"),
                ),
                path(
                    "catalogosunat/",
                    include("apps.catalogoSunat.urls", namespace="catalogosunat"),
                ),
                path("empresa/", include("apps.empresa.urls", namespace="empresa")),
            ]
        ),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/persona/models.py
import os
from datetime import datetime, date
from django.db import models
from django.forms import model_to_dict
from apps.catalogoSunat.models import TipoDocumentoIdentidad, Ubigeo


class Persona(models.Model):
    tipoDoc = models.ForeignKey(
        TipoDocumentoIdentidad,
        verbose_name="Tipo de Documento",
        on_delete=models.PROTECT,
    )
    numDoc = models.CharField(
        verbose_name="Numero Documento", unique=True, max_length=11
    )
    denominacion = models.CharField(
        verbose_name="Razón Social/Nombre y Apellidos",
        max_length=150,
        blank=True,
        null=True,
    )
    direccion = models.CharField(
        verbose_name="Dirección", max_length=255, blank=True, null=True
    )
    fijo = models.CharField(
        verbose_name="Teléfono fijo", blank=True, null=True, max_length=10
    )
    movilUno = models.PositiveIntegerField(
        verbose_name="Celular", blank=True, null=True
    )
    movilDos = models.PositiveIntegerField(
        verbose_name="Celular2", blank=True, null=True
    )
    correo = models.EmailField(
        verbose_name="Correo", max_length=250, blank=True, null=True
    )
    ubigueo = models.ForeignKey(Ubigeo, on_delete=models.PROTECT, blank=True, null=True)
    activo = models.BooleanField(default=True)
    ispersonal = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Persona"
        verbose_name_plural = "Personas"

    def __str__(self):
        # return if self.denominacion not is None: self.denominacion; ""
        data = self.denominacion
        if data is None:
            data = "-"
        return data

    def toJSON(self):
        item = model_to_dict(
            self,
            exclude=[
                "foto",
            ],
        )
        item["tipoDoc"] = self.tipoDoc.toJSON()
        return item


GENERO = (
    ("F", "Femenino"),
    ("M", "Masculino"),
)


def rutaNombreImagen(instance, filename):
    extencion = os.path.splitext(filename)[1][1:]
    fecha = datetime.today().strftime("%Y-%m-%d %H:%M:%S")
    return f"persona/{instance.persona.numDoc}-{fecha}." + extencion


class PersonaNatural(models.Model):
    persona = models.OneToOneField(
        Persona, on_delete=models.PROTECT, blank=True, null=True
    )
    nombres = models.CharField(max_length=100)
    apellidoP = models.CharField(max_length=100)
    apellidoM = models.CharField(max_length=100)
    fechaNac = models.DateField(
        verbose_name="Fecha de Nacimiento", blank=True, null=True
    )
    foto = models.ImageField(
        verbose_name="Foto",
        upload_to=rutaNombreImagen,
        default="persona/default.png",
        blank=True,
    )
    genero = models.CharField(
        verbose_name="Género", max_length=10, choices=GENERO, blank=True, null=True
    )
    ordenhappy = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        verbose_name = "PersonaNatural"
        verbose_name_plural = "PersonaNaturals"

    def __str__(self):
        return self.nombres

    def nombreCompleto(self):
        return f"{self.nombres}, {self.nombres} {self.nombres}"

    def saveOrdenCumpl(self):
        self.ordenhappy = self.fechaNac.strftime("%j")
        self.save(update_fields=["ordenhappy"])
        return self.ordenhappy

    def edad(self):
        try:
            edad = datetime.now().year - self.fechaNac.year
        except:
            edad = self.fechaNac

        return edad

    def happy(self):
        hoy = date.today()
        fecha_final = self.fechaNac
        try:
            fecha = fecha_final.replace(year=hoy.year)
            if hoy <= fecha:
                dif = fecha - hoy
                happy = dif.days
            else:
                fecha = fecha.replace(year=hoy.year + 1)
                dif = fecha - hoy
                happy = dif.days
        except Exception as e:
            print(str(e))
            happy = "No tiene FN"
        return happy


class PersonaJuridica(models.Model):
    persona = models.ForeignKey(Persona, on_delete=models.PROTECT)
    estado = models.BooleanField(default=True, blank=True, null=True)
    condicion = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        verbose_name = "PersonaJuridica"
        verbose_name_plural = "PersonaJuridicas"

    def __str__(self):
        return str(self.persona.id)

apps/persona/forms.py
from django import forms

from apps.persona.models import Persona, PersonaNatural


class PersonaForm(forms.ModelForm):
    # fechaNac = forms.CharField(label="Fecha de nacimiento",required=False,widget=forms.TextInput(attrs={'class': 'datepicker'}))

    class Meta:
        model = Persona
        fields = "__all__"

    def clean_fechaNac(self):
        fechanac = self.cleaned_data.get("fechaNac")
        if not fechanac:
            fechanac = None
        return fechanac

    def clean_numDoc(self):
        tipodoc = self.cleaned_data.get("tipoDoc")
        numdoc = len(str(self.cleaned_data.get("numDoc")))

        if tipodoc != None:
            if tipodoc.codigo == "6" and numdoc != 11:
                print("ruc")
                raise forms.ValidationError("El RUC tiene que tener 11 dígitos")
            elif tipodoc.codigo == "1" and numdoc != 8:
                print("dni")
                raise forms.ValidationError("El DNI tiene que tener 8 dígitos")
            else:
                pass
        return self.cleaned_data.get("numDoc")


class PersonaNaturalForm(forms.ModelForm):
    class Meta:
        model = PersonaNatural
        exclude = ("persona",)

        widgets = {"fechaNac": forms.DateInput(attrs={"type": "date"})}

apps/persona/API/views.py
from ..models import Persona, PersonaJuridica, PersonaNatural
from rest_framework.response import Response
from rest_framework import status
from rest_framework import generics
from .serializers import (
    PersonaJuridicaSerializerAPI,
    PersonaNaturalSerializerAPI,
    PersonaSerializer,
    PersonaSerializerAPI,
)
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.views import APIView


class PersonaListCreateAPIView(generics.ListCreateAPIView):
    queryset = Persona.objects.all()
    serializer_class = PersonaSerializer


class PersonaRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Persona.objects.all()
    serializer_class = PersonaSerializer


class PersonaViewSet(viewsets.ModelViewSet):
    """
    Vista para gestionar el CRUD de personas y la búsqueda por DNI.
    """

    queryset = Persona.objects.all()
    serializer_class = PersonaSerializerAPI

    @action(detail=False, methods=["get"], url_path="buscar-por-dni")
    def buscar_por_dni(self, request):
        """
        Consulta por DNI usando query params y devuelve el id de la persona.
        """
        dni = request.query_params.get("dni", None)
        if not dni:
            return Response(
                {"error": "El parámetro 'dni' es requerido."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        try:
            persona = Persona.objects.get(numDoc=dni)
            serializer = self.get_serializer(persona)
            return Response(serializer.data, status=status.HTTP_200_OK)
        except Persona.DoesNotExist:
            return Response(
                {"error": "No se encontró ninguna persona con el DNI proporcionado."},
                status=status.HTTP_404_NOT_FOUND,
            )

    def create(self, request, *args, **kwargs):
        """
        Crear un nuevo registro de Persona con la estructura requerida.
        """
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(
            serializer.data, status=status.HTTP_201_CREATED, headers=headers
        )


class PersonaNaturalAPIView(APIView):
    def post(self, request, *args, **kwargs):
        serializer = PersonaNaturalSerializerAPI(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get(self, request, *args, **kwargs):
        personas = PersonaNatural.objects.all()
        serializer = PersonaNaturalSerializerAPI(personas, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)


class PersonaJuridicaAPIView(APIView):
    def post(self, request, *args, **kwargs):
        serializer = PersonaJuridicaSerializerAPI(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get(self, request, *args, **kwargs):
        personas = PersonaJuridica.objects.all()
        serializer = PersonaJuridicaSerializerAPI(personas, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

templates/apps/persona/add.html
{% extends "layouts/base-demo.html" %}
{% load static %}

{% block title %} Register {% endblock %} 

<!-- Plugins CSS goes HERE  -->
{% block css %}
<style>
    .masOpcionVisible{        
        display: none;
    }
    input:required {
        background-color: yellow;
    }
    .search{
        cursor:pointer; 
        cursor: hand
    }
    #personajuridica{
        display: none;
    }
</style>
{% endblock css %}

{% block breadcrumb %}
<div class="nav-content px5 red lighten-1">
  <a href="#" class="breadcrumb">Home</a>
  <a href="{% url 'persona:list' %}" class="breadcrumb">Persona</a>
  <a href="#!" class="breadcrumb">Nuevo</a>
</div>
{% endblock breadcrumb %}

{% block content %}

    {% if form.errors %}
        {% for m in form.errors %}
        {{m}}        
        {% endfor %}  
    {% endif %}
    <div class="divider"></div>
    {% if form_natural.errors %}
        {% for m in form_natural.errors %}
        {{m}}        
        {% endfor %}  
    {% endif %}
    <div class="progress hide" id="preload">
        <div class="indeterminate"></div>
    </div>
    <div class="container">
        <div class="container">            
        <div class="row">
            <div class="col s12 m12 l12">
                
            <form method="POST" enctype="multipart/form-data" onsubmit="enviarForm(event)">
                {% csrf_token %}
              <div class="card">
                
                <div class="card-content white-text">
                    
                  <span class="card-title red-text">Nueva Persona</span>
                  
                  <div class="row">
                    <div class="input-field col s12 m12 l5">
                        {{form.tipoDoc}}
                        {{form.tipoDoc.label_tag}}
                        {{form.tipoDoc.errors}}                       
                    </div>
                    <div class="input-field col s12 m12 l7 " style="padding-right: 1em;">                        
                        {{form.numDoc}}
                        {{form.numDoc.label_tag}}                        
                        <i class="material-icons prefix red-text search">search</i> 
                        {{form.numDoc.errors}}                    
                    </div>
                    
                </div>
                <div class="" id="personajuridica">
                    <div class="row">
                        <div class="input-field col s12 m12 l12">
                            {{form.denominacion}}
                            {{form.denominacion.label_tag}}
                            {{form.denominacion.errors}}
                        </div>
                    </div>
                </div>
                <!-- persona natural-->
                <div class=" " id="personanatural">                
                    <div class="row">
                        <div class="input-field col s12 m4 l4">
                            {{form_natural.nombres}}
                            {{form_natural.nombres.label_tag}}
                            {{form_natural.nombres.errors}}
                        </div>
                        <div class="input-field col s12 m4 l4">
                            {{form_natural.apellidoP}}
                            {{form_natural.apellidoP.label_tag}}
                            {{form.apellidoP.errors}}
                        </div>
                        <div class="input-field col s12 m4 l4">
                            {{form_natural.apellidoM}}
                            {{form_natural.apellidoM.label_tag}}
                            {{form_natural.apellidoM.errors}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m6 l6">
                            {{form_natural.fechaNac}}
                            {{form_natural.fechaNac.label_tag}}
                            {{form_natural.fechaNac.errors}}
                        </div>
                        <div class="input-field col s12 m6 l6">
                            {{form_natural.genero}}
                            {{form_natural.genero.label_tag}}
                            {{form_natural.genero.errors}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="file-field input-field">
                            <div class="btn color-primary">
                                {{form_natural.foto.label}}
                                {{form_natural.foto}}
                            </div>
                            <div class="file-path-wrapper">
                            <input class="file-path validate" type="text">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- fin persona natural-->
                <div class="row">
                    <div class="input-field col s12 m12 l12">
                        {{form.direccion}}
                        {{form.direccion.label_tag}}
                        {{form.direccion.errors}}
                    </div>
                </div>


                <a href="#" id='masOpcion'>Ver más Opciones</a>
                
                <div class="masOpcionVisible">
                    <div class="divider"></div>
                    <div class="row">
                        <div class="input-field col s12 m12 l4">
                            {{form.fijo}}
                            {{form.fijo.label_tag}}
                        </div>
                        <div class="input-field col s12 m12 l4">
                            {{form.movilUno}}
                            {{form.movilUno.label_tag}}
                        </div>
                        <div class="input-field col s12 m12 l4">
                            {{form.movilDos}}
                            {{form.movilDos.label_tag}}
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12 m12 l12">
                            {{form.correo}}
                            {{form.correo.label_tag}}
                        </div>
                    </div>

                </div>

                </div>
                <div class="card-action">                    
                    <a href="{% url 'persona:list' %}" class="btn color-secundary">Cancelar</a>
                    <button class="btn waves-effect waves-light color-primary" id="btn-send" type="submit" name="action">Guardar
                        <i class="material-icons right">send</i>
                    </button> 
                </div>
              </div>
            </form>
            </div>
          </div>

    </div>
</div>

{% endblock content %}

{% block js %}

    <script>
        var cond = true
        
        $(document).ready(function(){            

            /*$('select').formSelect({
                isMultiple:true
            });*/
            

            $("#masOpcion").click(function(){
                
                if(cond) { $(".masOpcionVisible").css("display", "block"); cond=false}
                else{  $(".masOpcionVisible").css("display", "none"); cond=true}
               
            });

            $('#id_tipoDoc').removeAttr("required");
            $("input[type='text']").removeAttr("required");


        });  
    </script>

    {% if messages %}
    {% for m in messages %}
        <script>
            visibleAlert(
                title="Correcto!!",
                text="{{m}}",
                icon="{{m.tags}}"        
            )
        </script>
    {% endfor %}
    {% endif %}

    <script src="{% static 'js/apps/persona/persona.js' %}"></script>

{% endblock js %}


<!-- https://www.youtube.com/watch?v=wRNzGxbeuX8-->

templates/apps/persona/list.html
{% extends "layouts/base-demo.html" %}
{% load my_templatetag %}

{% block title %} Listar {% endblock %} 

{% block css %}
<style>
    td{
      padding: 3px 5px !important;
    }

  .contenedor{
    padding: 20px;;
  }

</style>

{% endblock css %}

{% block breadcrumb %}
<div class="nav-content px5 red lighten-1">
  <a href="{% url 'sistema:home-index' %}" class="breadcrumb">Home</a>
  <a href="{% url 'persona:list' %}" class="breadcrumb">Persona</a>
  <a href="#!" class="breadcrumb">Lista</a>
</div>
{% endblock breadcrumb %}


{% block content %}

<div class="row valign-wrapper">
    <div class="input-field col s12 m12 l6 block">
      <div class="row">
        <form  id="form_search" >   
          <div class="col s8">
            <input id="search" placeholder="Buscar por persona o documento" name="q" value="{{q}}">

          </div>
          <div class="col s4">
            <a id="btn-search" class="btn color-primary" href="{% url 'persona:list'  %}"><i class="material-icons left">search</i>Buscar</a>
          </div>
        </form>
      </div>
    
    </div>
  
    <div class="input-field col s12 m12 l6">
      <div class="right">
      <a  class="btn color-primary" href="{% url 'persona:add'  %}"><i class="material-icons left">add</i>Nueva Persona</a>
    </div>
    </div>
  
</div>
<div class="divider"></div>

<table id="table_idf" class="highlight responsive-table">
    <thead>
      <tr>
          <th>Item</th>
          <th>Denominación</th>
          <th>Tip Doc</th>
          <th>Numero</th>
          <th>Celular</th>
          <th>Correo</th>
          <th>Género</th>
          <th>Cumpleaños</th>

          <th>Activo</th>
          <th>Acción</th>
      </tr>
    </thead>

    <tbody>
      {% for persona in entity %}
      <tr>
        <td>{{forloop.counter}}</td>
        <td>{{persona.denominacion | nonep | capfirst }}</td>
        <td>{{persona.tipoDoc | nonep}}</td>
        <td>{{persona.numDoc | nonep}}</td>
        <td>{{persona.movilUno | nonep}}</td>
        <td>{{persona.correo | nonep}}</td>
        <td>{{persona.genero | nonep}}</td>
        
        {% if persona.personanatural.fechaNac %}
          <td>Faltan {{persona.personanatural.happy}} días[Cumpleaños] </td>
          {% else %}
          <td>- </td>
          {% endif %}
        
          
        
        <td>{{persona.activo | estado}}</td>
        <td>
          
            <a href="{% url 'persona:edit' persona.id %}" class="collection-item"><i class="material-icons left">edit</i></a>
            <!-- <a href="#!" class="collection-item "><i class="material-icons left color-primary-text">delete</i></a>-->
          
        </td>
      </tr>
      {% endfor %}
    </tbody>
</table>
  <div class="container center">
    {% include 'includes/paginator.html' %}
  </div>

  {% endblock content %}

  
  {% block js %}

      {% if messages %}
      {% for m in messages %}
          <script>
              visibleAlert(
                  title="",
                  text="{{m}}",
                  icon="{{m.tags}}"        
              )
          </script>
      {% endfor %}
      {% endif %}

      <script>
        
        $("#btn-search").click(function() {
          var q = $("#search").val()
          url = $(this).attr("href");
          window.open(url+"?q="+q,'_self');
          return false;
        })
      </script>

      <script>
        $(document).ready(function() {
    $('input#input_text, textarea#textarea2').characterCounter();
  });
      </script>

  {% endblock js %}
      