apps/empresa/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    ConductorAdd,
    ConductorList,
    AgenciaAdd,
    AgenciaList,
    AgenciaUpdate,
    ConductorUpdate,
)

app_name = "empresa"
urlpatterns = [
    path("conductor/add", login_required(ConductorAdd.as_view()), name="conductor-add"),
    path(
        "conductor/list", login_required(ConductorList.as_view()), name="conductor-list"
    ),
    path(
        "conductor/update/<int:pk>",
        login_required(ConductorUpdate.as_view()),
        name="conductor-update",
    ),
    path("agencia/add", login_required(AgenciaAdd.as_view()), name="agencia-add"),
    path("agencia/list", login_required(AgenciaList.as_view()), name="agencia-list"),
    path(
        "agencia/update/<int:pk>",
        login_required(AgenciaUpdate.as_view()),
        name="agencia-update",
    ),
]

apps/persona/urls.py
# persona/urls.py
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from .views import list, add, edit, autocomplite, updateOrdenHappy

app_name = "persona"

urlpatterns = [
    # Incluye las URLs de API desde el archivo separado
    path("api/", include("apps.persona.API.urls", namespace="api")),
    # Rutas no relacionadas con la API
    path("list/", (list), name="list"),
    path("add/", login_required(add), name="add"),
    path("edit/<int:pk>", login_required(edit), name="edit"),
    path("autocomplite/", login_required(autocomplite), name="autocomplite"),
    path(
        "update/orden/happy",
        login_required(updateOrdenHappy),
        name="update-orden-happy",
    ),
]

django_moda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Swagger
from drf_yasg import openapi
from drf_yasg.views import get_schema_view as swagger_get_schema_view


handler403 = "apps.sistema.views.custom_permission_denied_view"

schema_view = swagger_get_schema_view(
    openapi.Info(
        title="Moda Tours API",
        default_version="1.0",
        description="Moda Tours API Documentation",
    ),
    public=True,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("persona/", include("apps.persona.urls", namespace="persona")),
    path("envio/", include("apps.envio.urls", namespace="envio")),
    path("viaje/", include("apps.viaje.urls", namespace="viaje")),
    path("tesoreria/", include("apps.caja.urls", namespace="caja")),
    path("", include("apps.web.urls", namespace="web")),
    path("sistema/", include("apps.sistema.urls", namespace="sistema")),
    path("facturacion/", include("apps.facturacion.urls", namespace="facturacion")),
    path(
        "catalogosunat/", include("apps.catalogoSunat.urls", namespace="catalogosunat")
    ),
    path("empresa/", include("apps.empresa.urls", namespace="empresa")),
    path(
        "api/v1/",
        include(
            [
                path(
                    "swagger/schema/",
                    schema_view.with_ui("swagger", cache_timeout=0),
                    name="swagger-schema",
                ),
                path("persona/", include("apps.persona.urls", namespace="persona")),
                path("envio/", include("apps.envio.urls", namespace="envio")),
                path("viaje/", include("apps.viaje.urls", namespace="viaje")),
                path("tesoreria/", include("apps.caja.urls", namespace="caja")),
                path("", include("apps.web.urls", namespace="web")),
                path("sistema/", include("apps.sistema.urls", namespace="sistema")),
                path(
                    "facturacion/",
                    include("apps.facturacion.urls", namespace="facturacion"),
                ),
                path(
                    "catalogosunat/",
                    include("apps.catalogoSunat.urls", namespace="catalogosunat"),
                ),
                path("empresa/", include("apps.empresa.urls", namespace="empresa")),
            ]
        ),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/empresa/models.py
from django.db import models
from django.forms import model_to_dict
from apps.persona.models import Persona
from apps.catalogoSunat.models import Ubigeo, TipoDocumento


class Vehiculo(models.Model):
    placa = models.CharField(max_length=10)
    categoria = models.CharField(max_length=50, blank=True, null=True)
    marca = models.CharField(max_length=50)
    modelo = models.CharField(max_length=50)
    color = models.CharField(max_length=50)
    numSerie = models.CharField(max_length=50, blank=True, null=True)
    numMotor = models.CharField(max_length=50, blank=True, null=True)
    carroceria = models.CharField(max_length=50, blank=True, null=True)
    combustible = models.CharField(max_length=100, blank=True, null=True)
    numAsientos = models.IntegerField(blank=True, null=True)
    numPasajeros = models.IntegerField(blank=True, null=True)
    propio = models.BooleanField(default=False)
    numfilas = models.SmallIntegerField(blank=True, null=True, default=1)
    numColumnas = models.SmallIntegerField(blank=True, null=True, default=1)

    class Meta:
        verbose_name = "Vehiculo"
        verbose_name_plural = "Vehiculos"

    def __str__(self):
        return self.placa


Estado = {
    ("libre", "Libre"),
    ("cortesia", "Cortesía"),
    ("pasadiso", "Pasadiso"),
}


class Asiento(models.Model):
    codigoMatrix = models.SmallIntegerField(default=1)
    numero = models.CharField(
        verbose_name="Numero de asiento", max_length=2, blank=True, null=True
    )
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    saltofila = models.BooleanField(default=False)
    estado = models.CharField(
        max_length=20, null=True, blank=True, choices=Estado, default="libre"
    )

    class Meta:
        verbose_name = "Asiento"
        verbose_name_plural = "Asientos"

    def __str__(self):
        return str(self.codigoMatrix)

    def toJson(self):
        return model_to_dict(self)


class Conductor(models.Model):
    chofer = models.ForeignKey(Persona, on_delete=models.CASCADE)
    numLicencia = models.CharField(verbose_name="Nro de licencia", max_length=12)
    clase = models.CharField(max_length=1)
    categoria = models.CharField(max_length=5)
    fechaExpedicion = models.DateField(
        verbose_name="Fecha de expedición", blank=True, null=True
    )
    fechaRevalidacion = models.DateField(
        verbose_name="Fecha de revalidación", blank=True, null=True
    )
    activo = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Conductor"
        verbose_name_plural = "Conductors"

    def __str__(self):
        return self.chofer.denominacion


TIPO = (
    ("PRINCIPAL", "PRINCIPAL"),
    ("SUCURSAL", "SUCURSAL"),
)


class Agencia(models.Model):
    nombre = models.CharField(max_length=150, blank=True, null=True)
    ubigeo = models.ForeignKey(Ubigeo, on_delete=models.CASCADE)
    responsable = models.ForeignKey(
        Persona, on_delete=models.CASCADE, blank=True, null=True
    )
    empresa = models.ForeignKey(
        Persona,
        related_name="empresa_agencia",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    direccion = models.CharField(max_length=255, blank=True, null=True)
    fijo = models.CharField(max_length=9, blank=True, null=True)
    movilUno = models.CharField(
        verbose_name="Celular", max_length=9, blank=True, null=True
    )
    movilDos = models.CharField(max_length=9, blank=True, null=True)
    correo = models.EmailField(max_length=255, blank=True, null=True)
    tipo = models.CharField(max_length=10, choices=TIPO, blank=True, null=True)
    foto = models.ImageField(upload_to="media/agencia", blank=True, null=True)
    activo = models.BooleanField(default=True)
    codigoSerieDocumento = models.CharField(max_length=3, blank=True, null=True)
    isruta = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Agencia"
        verbose_name_plural = "Agencia"

    def __str__(self):
        return self.nombre


class AgenciaDocumento(models.Model):
    agencia = models.ForeignKey(Agencia, on_delete=models.PROTECT)
    documento = models.ForeignKey(TipoDocumento, on_delete=models.PROTECT)
    serie = models.CharField(max_length=4)
    correlativo = models.IntegerField()
    activo = models.BooleanField(default=True)

    class Meta:
        verbose_name = "AgenciaDocumento"
        verbose_name_plural = "AgenciaDocumentos"

    def __str__(self):
        return self.documento.descripcion

    def correlativoMas(self):
        correlativo = self.correlativo
        self.correlativo += 1
        self.save(update_fields=["correlativo"])
        return correlativo

    def correlativoMenos(self):
        correlativo = self.correlativo
        self.correlativo -= 1
        self.save(update_fields=["correlativo"])
        return correlativo

apps/empresa/forms.py
from django import forms
from .models import Conductor, Agencia


class ConductorForm(forms.ModelForm):
    class Meta:
        model = Conductor
        fields = "__all__"

        widgets = {
            "fechaExpedicion": forms.DateInput(attrs={"type": "date"}),
            "fechaRevalidacion": forms.DateInput(attrs={"type": "date"}),
        }


class AgenciaForm(forms.ModelForm):
    class Meta:
        model = Agencia
        exclude = ["empresa", "tipo"]

apps/empresa/views.py
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView
from apps.empresa.forms import ConductorForm, AgenciaForm
from apps.empresa.models import Agencia, Conductor


class ConductorList(ListView):
    model = Conductor
    paginate_by = 10
    context_object_name = "entity"
    template_name = "apps/empresa/conductor/list.html"

    def get_queryset(self):
        qs = super().get_queryset()
        q = self.request.GET.get("q", None)
        if q:
            qs = qs.filter(
                Q(chofer__denominacion__icontains=q) | Q(chofer__numDoc__icontains=q)
            ).distinct()

        return qs


class ConductorAdd(CreateView):
    model = Conductor
    form_class = ConductorForm
    success_url = reverse_lazy("empresa:conductor-list")
    template_name = "apps/empresa/conductor/add.html"


class ConductorUpdate(UpdateView):
    model = Conductor
    form_class = ConductorForm
    success_url = reverse_lazy("empresa:conductor-list")
    template_name = "apps/empresa/conductor/add.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["form"] = self.form_class(self.request.POST, instance=self.object)
        else:
            self.object = self.get_object()
            self.object.fechaExpedicion = (
                self.object.fechaExpedicion.isoformat()
                if self.object.fechaExpedicion
                else self.object.fechaExpedicion
            )
            self.object.fechaRevalidacion = (
                self.object.fechaRevalidacion.isoformat()
                if self.object.fechaRevalidacion
                else self.object.fechaRevalidacion
            )
            data["form"] = self.form_class(instance=self.object)
        return data


class AgenciaList(ListView):
    model = Agencia
    paginate_by = 10
    context_object_name = "entity"
    template_name = "apps/empresa/agencia/list.html"

    def get_queryset(self):
        qs = super().get_queryset()
        q = self.request.GET.get("q", None)
        if q:
            qs = qs.filter(nombre=q).distinct()

        return qs


class AgenciaAdd(CreateView):
    model = Agencia
    form_class = AgenciaForm
    success_url = reverse_lazy("empresa:agencia-list")
    template_name = "apps/empresa/agencia/add.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.empresa = Agencia.objects.filter(tipo="PRINCIPAL").first().empresa
        self.object.tipo = "SUCURSAL"
        return super().form_valid(form)


class AgenciaUpdate(UpdateView):
    model = Agencia
    form_class = AgenciaForm
    success_url = reverse_lazy("empresa:agencia-list")
    template_name = "apps/empresa/agencia/add.html"

templates/apps/empresa/agencia/add.html
{% extends "layouts/base-demo.html" %}
{% load static %}

{% block title %} Register {% endblock %} 

<!-- Plugins CSS goes HERE  -->
{% block css %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock css %}

{% block breadcrumb %}
<div class="nav-content px5 red lighten-1">
  <a href="#" class="breadcrumb">Home</a>
  <a href="{% url 'persona:list' %}" class="breadcrumb">Empresa</a>
  <a href="{% url 'persona:list' %}" class="breadcrumb">Agencia</a>
  <a href="#!" class="breadcrumb">Nuevo</a>
</div>
{% endblock breadcrumb %}

{% block content %}

    {% if form.errors %}
        {% for m in form.errors %}
        {{m}}        
        {% endfor %}  
    {% endif %}
    <div class="progress hide" id="preload">
        <div class="indeterminate"></div>
    </div>
    
    <div class="container">            
    <div class="row">
        <div class="col s12 m12 l12">
            
        <form method="POST" enctype="multipart/form-data" onsubmit="enviarForm(event)">
            {% csrf_token %}
            <div class="card">
            
            <div class="card-content white-text">
                <span class="card-title red-text">Nueva Agencia</span>
                <div class="row">
                    <div class="input-field col s12 m12 l4">
                        {{form.nombre}}
                        {{form.nombre.label_tag}}
                        {{form.nombre.errors}}                       
                    </div>
                    <div class="input-field col s12 m12 l5">
                        {{form.direccion}}
                        {{form.direccion.label_tag}}
                        {{form.direccion.errors}}                       
                    </div>
                    <div class="input-field col s12 m12 l3 ">                        
                        {{form.movilUno}}
                        {{form.movilUno.label_tag}}
                        {{form.movilUno.errors}}                    
                    </div>                      
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l12 ">                        
                        {{form.ubigeo}}
                        {{form.ubigeo.errors}}
                    </div>                        
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l2 ">                        
                        {{form.activo}}
                        {{form.activo.label_tag}}
                        {{form.activo.errors}}                    
                    </div>
                </div>

            </div>
            <div class="card-action">                    
                <a href="{% url 'persona:list' %}" class="btn color-secundary">Cancelar</a>
                <button class="btn waves-effect waves-light color-primary" id="btn-send" type="submit" name="action">Guardar
                    <i class="material-icons right">send</i>
                </button> 
            </div>
            </div>
        </form>
        </div>
        </div>

    </div>


{% endblock content %}

{% block js %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script>
        
        $(document).ready(function() {
        autocomplete('ubigeo','/catalogosunat/autocomplite/','Buscar Ubigeo');
    
    });
    </script>
   

{% endblock js %}


<!-- https://www.youtube.com/watch?v=wRNzGxbeuX8-->

templates/apps/empresa/agencia/list.html
{% extends "layouts/base-demo.html" %}
{% load my_templatetag %}

{% block title %} Listar {% endblock %} 

{% block css %}
<style>
    td{
      padding: 3px 5px !important;
    }

  .contenedor{
    padding: 20px;;
  }

</style>

{% endblock css %}

{% block breadcrumb %}
<div class="nav-content px5 red lighten-1">
  <a href="#" class="breadcrumb">Home</a>
  <a href="{% url 'persona:list' %}" class="breadcrumb">Empresa</a>
  <a href="{% url 'persona:list' %}" class="breadcrumb">Agencía</a>
  <a href="#!" class="breadcrumb">Lista</a>
</div>
{% endblock breadcrumb %}


{% block content %}

<div class="row valign-wrapper">
    <div class="input-field col s12 m12 l6 block">
      <div class="row">
        <form  id="form_search" >   
          <div class="col s8">
            <input id="search" placeholder="Buscar por persona o documento" name="q" value="{{q}}">

          </div>
          <div class="col s4">
            <a id="btn-search" class="btn color-primary" href="{% url 'persona:list'  %}"><i class="material-icons left">search</i>Buscar</a>
          </div>
        </form>
      </div>
    
    </div>
  
    <div class="input-field col s12 m12 l6">
      <div class="right">
      <a  class="btn color-primary" href="{% url 'empresa:agencia-add'  %}"><i class="material-icons left">add</i>Nueva Agencía</a>
    </div>
    </div>
  
</div>
<div class="divider"></div>

<table id="table_idf" class="highlight responsive-table">
    <thead>
      <tr>
          <th>Item</th>
          <th>Nombre</th>
          <th>Direccion</th>
          <th>Ubigueo</th>
          <th>Celular</th>
          <th>Tipo</th>
          <th>Estado</th>
          <th>Acciones</th>
      </tr>
    </thead>

    <tbody>
      {% for item in entity %}
      <tr>
        <td>{{forloop.counter}}</td>
        <td>{{item.nombre}}</td>
        <td>{{item.direccion}}</td>
        <td>{{item.ubigeo.ubigeo_completo}}</td>
        <td>{{item.movilUno}}</td>
        <td>{{item.tipo}}</td>
        <td>{{item.activo | estado}}</td>
        <td>
          
            <a href="{% url 'empresa:agencia-update' item.pk %}" class="collection-item"><i class="material-icons left">edit</i></a>
            <!-- <a href="#!" class="collection-item "><i class="material-icons left color-primary-text">delete</i></a>-->
          
        </td>
      </tr>
      {% endfor %}
    </tbody>
</table>
  <div class="container center">
    {% include 'includes/paginator-vista-clases.html' %}
  </div>

  {% endblock content %}

  
  {% block js %}

      {% if messages %}
      {% for m in messages %}
          <script>
              visibleAlert(
                  title="",
                  text="{{m}}",
                  icon="{{m.tags}}"        
              )
          </script>
      {% endfor %}
      {% endif %}

      <script>
        
        $("#btn-search").click(function() {
          var q = $("#search").val()
          url = $(this).attr("href");
          window.open(url+"?q="+q,'_self');
          return false;
        })
      </script>

      <script>
        $(document).ready(function() {
    $('input#input_text, textarea#textarea2').characterCounter();
  });
      </script>

  {% endblock js %}
      