apps/envio/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    encomiendaAdd,
    encomiendaList,
    liquidacionList,
    liquidacionAdd,
    liquidacionAddEncomienda,
    liquidacionPrint,
    liquidacionEdit,
    liquidacionSacarEncomienda,
    liquidacionRecepcion,
    liquidacionFinalizar,
    encomiendaRecepcion,
    encomiendaPrintA5,
)
from .views import encomiendaPrint

app_name = "envio"
urlpatterns = [
    path("encomienda/add/", login_required(encomiendaAdd), name="encomienda-add"),
    path("encomienda/list/", login_required(encomiendaList), name="encomienda-list"),
    path(
        "encomienda/recepcion/",
        login_required(encomiendaRecepcion),
        name="encomienda-recepcion",
    ),
    path("encomienda/print/", login_required(encomiendaPrint), name="encomienda-print"),
    path(
        "encomienda/print/A5/<int:encom_pk>/",
        login_required(encomiendaPrintA5),
        name="encomienda-print-a5",
    ),
    path("liquidacion/add/", login_required(liquidacionAdd), name="liquidacion-add"),
    path("liquidacion/list/", login_required(liquidacionList), name="liquidacion-list"),
    path("liquidacion/edit/", login_required(liquidacionEdit), name="liquidacion-edit"),
    path(
        "liquidacion/add/encomienda/",
        login_required(liquidacionAddEncomienda),
        name="liquidacion-add-encomienda",
    ),
    path(
        "liquidacion/sacar/encomienda/",
        login_required(liquidacionSacarEncomienda),
        name="liquidacion-sacar-encomienda",
    ),
    path(
        "liquidacion/finalizar/",
        login_required(liquidacionFinalizar),
        name="liquidacion-finalizar",
    ),
    path(
        "liquidacion/recepcion/",
        login_required(liquidacionRecepcion),
        name="liquidacion-recepcion",
    ),
    path(
        "liquidacion/print/", login_required(liquidacionPrint), name="liquidacion-print"
    ),
]

apps/facturacion/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import boletaPrint, list, enviarOse, detallePrint, ComprobanteExcel

app_name = "facturacion"
urlpatterns = [
    path("list/", login_required(list), name="list"),
    path("boleta/print/", login_required(boletaPrint), name="boleta-print"),
    path("detalle/print/", login_required(detallePrint), name="detalle-print"),
    path("enviar/ose/<int:pk>", login_required(enviarOse), name="enviar-ose"),
    path(
        "comprobante/excel/", login_required(ComprobanteExcel), name="comprobante-excel"
    ),
]

apps/sistema/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    userAdd,
    userList,
    accountLogin,
    accountLoggout,
    menuList,
    userAgencia,
    homeIndex,
)

app_name = "sistema"
urlpatterns = [
    path("user/add", login_required(userAdd), name="user-add"),
    path("user/list", login_required(userList), name="user-list"),
    path("user/agencia/list", login_required(userAgencia), name="user-agencia-list"),
    path("account/login", accountLogin, name="account-login"),
    path("account/loggout", login_required(accountLoggout), name="account-loggout"),
    path("menu/list", login_required(menuList), name="menu-list"),
    path("", login_required(homeIndex), name="home-index"),
]

django_moda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Swagger
from drf_yasg import openapi
from drf_yasg.views import get_schema_view as swagger_get_schema_view


handler403 = "apps.sistema.views.custom_permission_denied_view"

schema_view = swagger_get_schema_view(
    openapi.Info(
        title="Moda Tours API",
        default_version="1.0",
        description="Moda Tours API Documentation",
    ),
    public=True,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("persona/", include("apps.persona.urls", namespace="persona")),
    path("envio/", include("apps.envio.urls", namespace="envio")),
    path("viaje/", include("apps.viaje.urls", namespace="viaje")),
    path("tesoreria/", include("apps.caja.urls", namespace="caja")),
    path("", include("apps.web.urls", namespace="web")),
    path("sistema/", include("apps.sistema.urls", namespace="sistema")),
    path("facturacion/", include("apps.facturacion.urls", namespace="facturacion")),
    path(
        "catalogosunat/", include("apps.catalogoSunat.urls", namespace="catalogosunat")
    ),
    path("empresa/", include("apps.empresa.urls", namespace="empresa")),
    path(
        "api/v1/",
        include(
            [
                path(
                    "swagger/schema/",
                    schema_view.with_ui("swagger", cache_timeout=0),
                    name="swagger-schema",
                ),
                path("persona/", include("apps.persona.urls", namespace="persona")),
                path("envio/", include("apps.envio.urls", namespace="envio")),
                path("viaje/", include("apps.viaje.urls", namespace="viaje")),
                path("tesoreria/", include("apps.caja.urls", namespace="caja")),
                path("", include("apps.web.urls", namespace="web")),
                path("sistema/", include("apps.sistema.urls", namespace="sistema")),
                path(
                    "facturacion/",
                    include("apps.facturacion.urls", namespace="facturacion"),
                ),
                path(
                    "catalogosunat/",
                    include("apps.catalogoSunat.urls", namespace="catalogosunat"),
                ),
                path("empresa/", include("apps.empresa.urls", namespace="empresa")),
            ]
        ),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/facturacion/models.py
from django.db import models
from apps.catalogoSunat.models import TipoDocumento
from apps.persona.models import Persona
from apps.venta.models import Movimiento

"""
class DocumentoOse(models.Model):
    pass
    venta = models.OneToOneField(Venta)
    operacion = models.CharField(max_length=11, default='generar_comprobante')
    tipo_de_comprobante = models.IntegerField(max_length=1)
    serie = models.CharField(max_length=4)
    numero = models.IntegerField(max_length=8)
    sunat_transaction = models.IntegerField(max_length=1)
    cliente_tipo_de_documento = models.CharField(max_length=1)
    cliente_numero_de_documento = models.CharField(max_length=15)
    cliente_denominacion = models.CharField(verbose_name='Razon Social/Nombre Completo',max_length=100)
    cliente_direccion = models.CharField(verbose_name='Direccion Completa|F~B',max_length=100)
    cliente_email = models.EmailField(max_length=250, blank=True,null=True)
    cliente_email_1 = models.EmailField(max_length=250, blank=True,null=True)
    cliente_email_2 = models.EmailField(max_length=250, blank=True,null=True)
    fecha_de_emision = models.DateField()
    fecha_de_vencimiento = models.DateField()
    moneda = models.IntegerField(max_length=1)
    tipo_de_cambio = models.DecimalField(max_digits=4,decimal_places=3, blank=True,null=True ) #condicional si ~PEN
    porcentaje_de_igv = models.DecimalField(max_digits=4,decimal_places=2, default=18.00)
    descuento_global = models.DecimalField(max_digits=14,decimal_places=2, blank=True,null=True)
    total_descuento = models.DecimalField(max_digits=14,decimal_places=2, blank=True,null=True)
    total_anticipo = models.DecimalField(max_digits=14,decimal_places=2, blank=True,null=True)
    total_gravada = models.DecimalField(max_digits=14,decimal_places=2, blank=True,null=True)
    total_inafecta = models.DecimalField(max_digits=14,decimal_places=2, blank=True,null=True)
    total_exonerada = models.DecimalField(max_digits=14,decimal_places=2, blank=True,null=True)
    total_igv = models.DecimalField(max_digits=14,decimal_places=2, blank=True,null=True)
    total_gratuita = models.DecimalField(max_digits=14,decimal_places=2, blank=True,null=True)
    total_otros_cargos = models.DecimalField(max_digits=14,decimal_places=2, blank=True,null=True)
    total_isc = models.DecimalField(max_digits=14,decimal_places=2, blank=True,null=True)
    total = models.DecimalField(max_digits=14,decimal_places=2)
    percepcion_tipo = models.SmallIntegerField(max_length=1, blank=True,null=True)
    percepcion_base_imponible = models.DecimalField(max_digits=14,decimal_places=2, blank=True,null=True)
    total_percepcion = models.DecimalField(max_digits=14,decimal_places=2, blank=True,null=True)
    total_incluido_percepcion = models.DecimalField(max_digits=14,decimal_places=2,blank=True,null=True)
    retencion_tipo = models.SmallIntegerField(max_length=1,choices=[(1,'TASA 3%'),(2,'TASA 6%')], blank=True,null=True)
    retencion_base_imponible = models.DecimalField(max_digits=14,decimal_places=2, blank=True,null=True)
    total_retencion = models.DecimalField(max_digits=14,decimal_places=2, blank=True,null=True)
    total_impuestos_bolsas = models.DecimalField(max_digits=14,decimal_places=2, blank=True,null=True)
    detraccion = models.CharField(max_length=5,choices=[('false','FALSO'),('true','VERDADERO')], blank=True,null=True)
    observaciones = models.TextField(max_length=1000, blank=True,null=True)
    documento_que_se_modifica_tipo = models.SmallIntegerField(max_length=1, choices=[(1,'FACTURAS ELECTRÓNICA'),(2,'BOLETAS DE VENTA ELECTRÓNICAS')], blank=True,null=True)
    documento_que_se_modifica_serie = models.CharField(max_length=4,blank=True,null=True)
    documento_que_se_modifica_numero = models.IntegerField(max_length=8,blank=True,null=True)
    tipo_de_nota_de_credito = models.IntegerField(max_length=2,blank=True,null=True)
    tipo_de_nota_de_debito = models.IntegerField(max_length=2,blank=True,null=True)
    enviar_automaticamente_a_la_sunat =  models.CharField(max_length=5,choices=[('false','FALSO'),('true','VERDADERO')], blank=True,null=True)
    enviar_automaticamente_al_cliente =  models.CharField(max_length=5,choices=[('false','FALSO'),('true','VERDADERO')], blank=True,null=True)
    codigo_unico = models.CharField(max_length=20,blank=True,null=True)
    condiciones_de_pago = models.CharField(max_length=250,blank=True,null=True)
    medio_de_pago = models.CharField(max_length=250,blank=True,null=True)
    placa_vehiculo = models.CharField(max_length=8,blank=True,null=True)
    orden_compra_servicio  = models.CharField(max_length=20,blank=True,null=True)
    formato_de_pdf = models.CharField(max_length=6,choices=[('A4','A4'),('A5','A5'),('TICKET','TICKET')])
    generado_por_contingencia = models.CharField(max_length=5,choices=[('false','FALSO'),('true','VERDADERO')], blank=True,null=True)
    bienes_region_selva = models.CharField(max_length=5,choices=[('false','FALSO'),('true','VERDADERO')], blank=True,null=True)
    servicios_region_selva = models.CharField(max_length=5,choices=[('false','FALSO'),('true','VERDADERO')], blank=True,null=True)


    class Meta:
        verbose_name = 'Documento'
        verbose_name_plural = 'Documentos'

    def __str__(self):
        return self.cliente_denominacion
    
class ItemOse(models.Model):
    documento = models.ForeignKey(Documento, on_delete=models.PROTECT)
    unidad_de_medida = models.CharField(max_length=5,choices=[('NIU','PRODUCTO'),('ZZ','SERVICIO')])
    codigo = models.CharField(max_length=250,blank=True,null=True)
    codigo_producto_sunat = models.CharField(max_length=8,blank=True,null=True)
    descripcion = models.TextField(max_length=250)
    cantidad = models.DecimalField(max_digits=14,decimal_places=2)
    valor_unitario = models.DecimalField(max_digits=14,decimal_places=2) #sin igv | pre_uni/1.18
    precio_unitario = models.DecimalField(max_digits=14,decimal_places=2) #con igv | val_uni*1.18
    descuento = models.DecimalField(max_digits=14,decimal_places=2,blank=True,null=True) #desc antes de los impuestos
    subtotal = models.DecimalField(max_digits=14,decimal_places=2) #val_uni*cantidad-desc
    tipo_de_igv = models.SmallIntegerField(max_length=2)
    tipo_de_ivap = models.CharField(max_length=3,blank=True,null=True,choices=[('17','IVAP Gravado'),('101','IVAP Gratuito')])
    igv = models.DecimalField(max_digits=14,decimal_places=2) #Total igv de linea
    impuesto_bolsas = models.DecimalField(max_digits=14,decimal_places=2,blank=True,null=True,) 
    total = models.DecimalField(max_digits=14,decimal_places=2) 
    anticipo_regularizacion = models.CharField(max_length=5,choices=[('false','FALSO'),('true','VERDADERO')])
    anticipo_documento_serie = models.CharField(max_length=4,blank=True,null=True)
    anticipo_documento_numero = models.IntegerField(max_length=8,blank=True,null=True)
    tipo_de_isc = models.DecimalField(max_digits=14,decimal_places=2,blank=True,null=True,) 
    isc = models.DecimalField(max_digits=14,decimal_places=2,blank=True,null=True,) 

    class Meta:

        verbose_name = 'Item'
        verbose_name_plural = 'Items'

    def __str__(self):
        return self.descripcion


class VentaCreditoOse(models.Model):
    documento = models.ForeignKey(Documento, on_delete=models.PROTECT)
    cuota = models.SmallIntegerField(max_length=3)
    fecha_de_pago = models.DateField()
    importe = models.DecimalField(max_digits=14,decimal_places=2)

    class Meta:

        verbose_name = 'VentaCredito'
        verbose_name_plural = 'VentaCreditos'

    def __str__(self):
        return str(self.importe)

class GuiaOse(models.Model):

    documento = models.ForeignKey(Documento, on_delete=models.PROTECT)
    guia_tipo = models.SmallIntegerField(max_length=1,choices=[(1,'GUÍA DE REMISIÓN REMITENTE'),(2,'GUÍA DE REMISIÓN TRANSPORTISTA')])
    guia_serie_numero = models.CharField(max_length=30)#serie-numero numeros propios


    class Meta:

        verbose_name = 'Guia'
        verbose_name_plural = 'Guias'

    def __str__(self):
        return self.guia_tipo

"""

"""class FacturaBoleta(models.Model):
    vendedor = models.ForeignKey(Persona, on_delete=models.PROTECT)
    venta = models.OneToOneField(Venta)    
    tipoComprobante = models.CharField(max_length=2)
    serieComprobante = models.CharField(max_length=4)
    numComprobante = models.IntegerField(max_length=8)
    tipOperacion = models.ForeignKey(TipoOperacion, on_delete=models.PROTECT)#catalogo51
    fecEmision = models.DateField(auto_now=True)
    horEmision = models.TimeField(auto_now=True)
    fecVencimiento =  models.DateField(null=True,blank=True)    
    tipMoneda = models.ForeignKey(TipoMonedaIso, on_delete=models.PROTECT) # catalogo 2
    cliente = models.ForeignKey(Persona, on_delete=models.PROTECT) #11 12 13
    totalGravadas
    totalInafectas
    totalExoneradas
    totalGratuitas
    sumIgv
    totalTributos
    totaValorVenta
    subTotalFactura
    importeTotalVenta
    leyenda = models.ForeignKey(Leyenda, on_delete=models.PROTECT)



    class Meta:

        verbose_name = 'FacturaBoleta'
        verbose_name_plural = 'FacturaBoletas'

    def __str__(self):

class FacturaBoletaItem(models.Model):
    unidadMedida
    cantidad
    descripcion
    valorUnitario
    precioUnitario
    afectacionIgv  #catalogo 07
    porcentajeDescuento
    montoDescuento
    valorVenta
    totalTributos

    class Meta:
        verbose_name = 'FacturaBoletaItem'
        verbose_name_plural = 'FacturaBoletaItems'

    def __str__(self):
"""


# documento
class FaturaBoleta(models.Model):
    ventaMovimiento = models.OneToOneField(
        Movimiento, on_delete=models.PROTECT, blank=True, null=True
    )
    tipoDocumento = models.ForeignKey(TipoDocumento, on_delete=models.PROTECT)
    serie = models.CharField(max_length=4, blank=True, null=True)
    numero = models.IntegerField(blank=True, null=True)

apps/facturacion/forms.py
from django import forms
from .models import FaturaBoleta
from apps.catalogoSunat.models import TipoDocumento
from apps.persona.models import Persona


class FacturaBoletaForm(forms.ModelForm):
    cliente = forms.ModelChoiceField(queryset=Persona.objects.all())

    class Meta:
        model = FaturaBoleta
        fields = "__all__"

        widgets = {
            "tipoDocumento": forms.Select(attrs={"class": "select"}),
            "cliente": forms.Select(attrs={"class": "select"}),
        }

    def clean(self):
        cleaned_data = super(FacturaBoletaForm, self).clean()

        tdoc = cleaned_data.get("tipoDocumento", None)
        clie = cleaned_data.get("cliente", None)
        if tdoc is not None and clie is not None:
            if tdoc.codigo == "01" and clie.tipoDoc.codigo != "6":
                self.add_error("cliente", "El Cliente debe ser persona juridica")
                # raise forms.ValidationError('El Cliente debe ser persona juridica')
            elif tdoc.codigo == "03" and clie.tipoDoc.codigo != "1":
                self.add_error("cliente", "El Cliente debe ser persona natural")
                # raise forms.ValidationError('El Cliente debe ser persona natural')

    def __init__(self, *args, **kwargs):
        # Extraer cliente del kwargs o inicial
        cliente_inicial = kwargs.pop("cliente", None)

        super(FacturaBoletaForm, self).__init__(*args, **kwargs)
        self.fields["tipoDocumento"].queryset = TipoDocumento.objects.filter(
            activo=True
        )
        # Si se proporciona un cliente, configurar el queryset para solo ese cliente
        if cliente_inicial:
            self.fields["cliente"].queryset = Persona.objects.filter(
                pk=cliente_inicial.id
            )
            self.initial["cliente"] = (
                cliente_inicial  # Establecer cliente inicial en el formulario
            )

templates/apps/facturacion/embarque.html
{% load static %}
    <img id="logo" src=" {% static 'img/logo-oficial-red.svg' %}" alt="Girl in a jacket" width="200" height="80">
    <p class="centrado"><b>MODA TOURS S.A.C</b></p>
    <p class="centrado">
        {{movimiento.agencia.direccion}} <br>
        {{movimiento.agencia.ubigeo.ubigeo_completo}}<br>
        RUC: &nbsp; {{movimiento.agencia.empresa.numDoc}}<br>
        TELÉFONO: <tel>{{movimiento.agencia.movilUno}}</tel>
    </p>
    <br>
    <p class="centrado"><b>EMBARQUE N°.000{{movimiento.embarque.numDocumento}}</b></p>
    <div class="divider"></div>

    <p class=""><b>PASAJERO:</b> {{movimiento.embarque.pasajero | upper}}</p>
    <p class=""><b>N° DOC:</b> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{movimiento.embarque.pasajero.numDoc}}</p>
    <p class=""><b>ORIGEN:</b> &nbsp;&nbsp;&nbsp;&nbsp; {{movimiento.embarque.lugar_abordo}}</p>
    <p class=""><b>DESTINO:</b> &nbsp;&nbsp;&nbsp; {{movimiento.embarque.lugar_bajada}}</p>                   
    <p><b>N° ASIENTO:</b> &nbsp;&nbsp;&nbsp;&nbsp; {{movimiento.embarque.numAsiento | title}}</p>
    <p><b>FECHA DE VIAJE:</b> &nbsp; {{movimiento.embarque.programacionViaje.fechaViaje}}</p>
    <p><b>HORA DE VIAJE:</b> &nbsp;&nbsp;&nbsp; {{movimiento.embarque.hora_abordo}} </p>
    <p><b>TELÉFONO:</b> &nbsp;&nbsp; {{movimiento.embarque.telefono}}</p>                            
    
    <br>
    <div class="divider"></div>
    <p><b>F.Emisión</b>:&nbsp; {{movimiento.create | date:'d/m/Y'}} | {{movimiento.create | date:'H:i'}}</p> 
    <br>
    <div class=" section">
        <p class="center"><b>IMPORTANTE:</b></p>
        <p class="centrado"><b>SE RECOMIENDA ESTAR 1 HORA ANTES DEL VIAJE.<br>
            EN TODO CASO PERDERÁ SU VIAJE Y NO HAY DEVOLUCIONES DE DINERO.</b>
        </p>
    </div>

    <p class="centrado">¡GRACIAS POR SU PREFERENCÍA!</p>
    <br><br>
    
    {% if image_qr is not None %}
        {{ image_qr|safe }}
    {% endif %}
        
    
    

templates/apps/facturacion/enviar-ose.html
{% extends "layouts/base-demo.html" %}
{% load my_templatetag %}
{% load static %}

{% block title %} Listar {% endblock %} 

{% block css %}
<style>
    td{
      padding: 3px 5px !important;
    }

  .contenedor{
    padding: 20px;;
  }

</style>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock css %}

{% block breadcrumb %}
<div class="nav-content px5 red lighten-1">
  <a href="#" class="breadcrumb">Home</a>
  <a href="{% url 'persona:list' %}" class="breadcrumb">Facturación</a>
  <a href="#!" class="breadcrumb">Enviar</a>
  <a href="#!" class="breadcrumb">Ose</a>
</div>
{% endblock breadcrumb %}


{% block content %}

<div class="progress hide" id="preload">
  <div class="indeterminate"></div>
</div>

<form method="POST" onsubmit="enviarForm(event)">
  {% csrf_token %}

  <div class="card">
      <div class="card-content white-text">

          <span class="card-title red-text">Facturacion.  N° 00001</span> 

      </div>
      <div class="divider"></div>
      <div class="card-content white-text">
          <p class="pb2 blue-text right" style="margin-bottom: 10px; font-size: 2rem;"> Monto: S/. <span id="id_monto">{{ montoCobrar }}</span></p>
          
          <div class="row">
              <div class="input-field col s12 m12 l12">
                  {{factura.tipoDocumento}}
                  {{factura.tipoDocumento.label_tag}}
                  {{factura.tipoDocumento.errors}} 
              </div>
          </div>
          <div class="row">
              <div class="input-field col s12 m12 l12">
                  {{factura.cliente}}
                  {{factura.cliente.errors}} 
              </div>
          </div>
          <div class="row">
              <div class="input-field col s12 m12 l12 grey" id="poblarSelect">
                  
              </div>
          </div>

      </div>
  <div class="card-action">                    
      <a href="#" class="btn color-secundary">Cancelar</a>
      <button class="btn waves-effect waves-light color-primary " id="btn-send" type="submit" name="action">Guardar
          <i class="material-icons right">send</i>
      </button>

      
    </div>

  </div>
  </div>


</form>
</div>
{% endblock content %}

  
  {% block js %}


      {% if messages %}
      {% for m in messages %}
          <script>
              visibleAlert(
                  title="",
                  text="{{factura.errors}}",
                  icon="{{m.tags}}"        
              )
          </script>
      {% endfor %}
      {% endif %}

      


      <script>
    $(document).ready(function() {
      $('#id_tipoDocumento').removeAttr("required");
      $('#id_cliente').removeAttr("required");

    $('.select').formSelect();
    autocomplete('cliente','/persona/autocomplite/','Buscar Cliente...')
    .on('select2:select', function (e) { 
        console.log('select event '+ e);
        poblarSelect = document.querySelector('#poblarSelect')
        poblarSelect.innerHTML = `<p>
                                    Tipo doc : ${e.params.data.tipoDoc.descripcion}<br>
                                    Num doc : ${e.params.data.numDoc}<br>
                                    Direccion : ${e.params.data.direccion}
                                    </p>`
        /*for (const property in e.params.data.tipoDoc) {
            console.log(`${property}: ${e.params.data.tipoDoc[property]}`);
          }*/
    });
})
      </script>
<script src="{% static 'js/apps/facturacion/enviar-ose.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  {% endblock js %}
      

templates/apps/facturacion/list.html
{% extends "layouts/base-demo.html" %}
{% load my_templatetag %}
{% load static %}

{% block title %} Listar {% endblock %} 

{% block css %}
<style>
    td{
      padding: 3px 5px !important;
    }

  .contenedor{
    padding: 20px;;
  }

</style>

{% endblock css %}

{% block breadcrumb %}
<div class="nav-content px5 red lighten-1">
  <a href="{% url 'sistema:home-index' %}" class="breadcrumb">Home</a>
  <a href="{% url 'persona:list' %}" class="breadcrumb">Facturación</a>
  <a href="#!" class="breadcrumb">Lista</a>
</div>
{% endblock breadcrumb %}


{% block content %}

<div class="row valign-wrapper">
    <div class="col s12 m12 l4 ">
        <form  id="form_search" >
          <div class="input-field">
            <input type="text" id="search" class="validate" placeholder="Buscar por persona o documento" name="q" value="{{q}}">
            <label for="icon_prefix">Buscar</label>
            <i class="material-icons prefix green-text">search</i> 
          </div>
        </form>
    </div>
    <div class=" col s12 m12 l5 center">
      
      <div class="input-field ">
        <form action="{% url 'facturacion:comprobante-excel' %}" id="form-descarga-excel"  onsubmit="descargar_excel(event)">     
          <input type="month" name="periodo" required="" id="id_periodo">
          <button class="btn-small waves-effect waves-light blue" type="submit" name="action" value="error" id="btn-send">EXCEL
            <i class="material-icons right">cloud_download</i>
          </button>
        </form> 
      </div>
      
    </div> 
    <div class=" col s12 m12 l3 ">
      <a  class="btn-small color-primary right" href="#"><i class="material-icons left">add</i>Nuevo Comprobante</a>
    </div> 
</div>
<div class="divider"></div>

<table id="table_idf" class="highlight responsive-table">
    <thead>
      <tr>
          <th>Item</th>
          <th>Comprob</th>
          <th>Serie</th>
          <th>Numero</th>
          <th>Cliente</th>
          <th>Tipo doc</th>
          <th>Num doc</th>
          <th>Monto</th>
          <th>Fecha</th>
          <th>Facturado</th>
          <th>Canje</th>
          <th colspan="2" class="center">Acción</th>
      </tr>
    </thead>

    <tbody>
      {% for factura in entity %}
      <tr>
        <td>{{forloop.counter}}</td>
        <td>{{factura.tipoDocumento }}</td>
        <td>{{factura.serie | nonep}}</td>
        <td>{{factura.numero | nonep}}</td>
        <td>{{factura.cliente | capfirst}}</td>
        <td>{{factura.cliente.tipoDoc }}</td>
        <td>{{factura.cliente.numDoc }}</td>
        <td>{{factura.monto}}</td>
        <td>{{factura.fechaFact | date:'d/m/Y'}}</td>
        <td>{{factura.estaFacturado | estadosino}}</td>
        <td>{{factura.iscanje | estadosino}}</td>
        <td>           
            <a href="/facturacion/detalle/print/?fromCityName=chintucaycuri%2520%2528Todos%2529%26fromCityId%3D195648&tipomovi={{factura.ventaMovimiento.movimientocaja.tipoMov.nombre}}&toCityName=Lima%2520%2528Todos%2529%26toCityId%3D195105%26onward%3D20-Jan-2022%26srcCountry%3DPER&mov={{factura.ventaMovimiento.id}}&destCountry=PER%26opId%3D0%26busType%3DAny" class="collection-item "><i class="material-icons left color-primary-text">print</i></a>
        </td>
        <td>
            <!--factura.ventaMovimiento.id-->            
            {% if not factura.estaFacturado %}
              <a href="{% url 'facturacion:enviar-ose' factura.ventaMovimiento.id %}" class="collection-item enviar-ose"><i class="material-icons left">cloud_queue</i></a>
            {% endif %}   
        </td>
        
      </tr>
      {% endfor %}
    </tbody>
</table>
  <div class="container center">
    {% include 'includes/paginator.html' %}
  </div>

  {% endblock content %}

  
  {% block js %}

  {% if messages %}
  {% for m in messages %}
      <script>
          visibleAlert(
              title="",
              text="{{m}}",
              icon="{{m.tags}}"        
          )
      </script>
  {% endfor %}
   
{% endif %}

      <script>
        
        $("#btn-search").click(function() {
          var q = $("#search").val()
          url = $(this).attr("href");
          window.open(url+"?q="+q,'_self');
          return false;
        })
      </script>

    <script src="{% static 'js/apps/facturacion/enviar-ose.js' %}"></script>

  {% endblock js %}
      